name: pdf
description: "A Flutter app for studying math with PDFs."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  syncfusion_flutter_pdfviewer: ^26.1.39
  google_generative_ai: ^0.4.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

dependency_overrides:
  intl: 0.20.2

flutter:
  # Bu satırı ekleyin
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/pdfs/