name: math_labs_flutter
description: "A Flutter app for studying math with PDFs and an AI assistant."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  syncfusion_flutter_pdfviewer: ^29.2.10
  google_generative_ai: ^0.4.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/pdfs/